onehashai/onehash-cal

- yarn.lock
> ch: yarn.lock

- packages/emails/src/components/EmailBodyLogo.tsx
- packages/lib/constants.ts
> mail changes

- apps/web/pages/signup.tsx
- apps/web/public/static/locales/en/common.json
- packages/features/auth/lib/isPasswordValid.ts
> password fixed

- packages/lib/hooks/useHasPaidPlan.ts
> updated teams billing

- packages/lib/constants.ts
- packages/ui/components/credits/Credits.tsx
> credits fix

- packages/lib/constants.ts
> ch: constants.ts

- packages/features/shell/Shell.tsx
- packages/ui/components/credits/Credits.tsx
- packages/ui/components/privacy-policy/PrivacyPolicy.tsx
- packages/ui/components/privacy-policy/index.ts
- packages/ui/index.tsx
> added privacy policy

- packages/app-store/stripepayment/lib/team-billing.ts
- packages/features/ee/organizations/pages/settings/general.tsx
> fix: ee/organizations/pages/settings/general.tsx

- apps/api/lib/helpers/verifyApiKey.ts
- apps/web/pages/booking/[uid].tsx
- packages/features/auth/lib/getServerSession.ts
- packages/features/auth/lib/next-auth-options.ts
> fixed: save webhook

- apps/web/pages/api/integrations/outlookcalendar/.well-known/microsoft-identity-association.json
> added outlookcalendar json

- packages/trpc/server/routers/viewer/teams/delete.handler.ts
- packages/trpc/server/routers/viewer/teams/removeMember.handler.ts
> removed user/delete team logic

- apps/web/components/onehash-chat-widget/OneHashChatWidget.tsx
- apps/web/pages/_app.tsx
- apps/web/pages/api/integrations/outlookcalendar/.well-known/microsoft-identity-association.json
- apps/web/pages/event-types/index.tsx
- packages/app-store/zoomvideo/api/deauthorize.ts
> chat support

- apps/web/pages/event-types/index.tsx
- packages/features/ee/support/lib/onehashchat/OneHashChatScript.tsx
- packages/features/shell/Shell.tsx
> added chat support

- apps/web/pages/signup.tsx
- packages/features/auth/lib/next-auth-options.ts
> sso added to signup page

- packages/features/oe/workflows/components/EventWorkflowsTab.tsx
> event type workflow page fix

- apps/web/pages/auth/login.tsx
- packages/features/auth/lib/federatedLogout.ts
- packages/features/shell/Shell.tsx
- packages/prisma/.env
> signOut added to shell.tsx

- apps/web/components/dialog/MeetingNotesDialog.tsx
- apps/web/components/getting-started/components/AppConnectionItem.tsx
- apps/web/components/getting-started/steps-views/ConnectCalendars.tsx
- apps/web/components/getting-started/steps-views/ConnectedVideoStep.tsx
- apps/web/components/getting-started/steps-views/ImportData.tsx
- apps/web/components/getting-started/steps-views/SetupAvailability.tsx
- apps/web/components/getting-started/steps-views/UserProfile.tsx
- apps/web/components/getting-started/steps-views/UserSettings.tsx
- apps/web/components/ui/UsernameAvailability/UsernameTextfield.tsx
- apps/web/components/ui/UsernameAvailability/index.tsx
- apps/web/lib/apps/installed/[category]/getServerSideProps.tsx
- apps/web/lib/apps/installed/getServerSideProps.tsx
- apps/web/lib/getting-started/[[...step]]/getServerSideProps.tsx
- apps/web/middleware.ts
- apps/web/pages/api/integrations/[...args].ts
- apps/web/pages/index.tsx
- apps/web/pages/settings/my-account/profile.tsx
- packages/app-store/_utils/useAddAppMutation.ts
- packages/app-store/components.tsx
- packages/app-store/googlecalendar/api/callback.ts
- packages/features/auth/lib/federatedLogout.ts
- packages/lib/server/checkRegularUsername.ts
- packages/lib/server/repository/profile.ts
- packages/lib/server/repository/user.ts
> Fix: User On-boarding

- apps/web/components/getting-started/steps-views/UserSettings.tsx
- apps/web/components/ui/UsernameAvailability/UsernameTextfield.tsx
- apps/web/components/ui/UsernameAvailability/index.tsx
- apps/web/lib/fpixel.ts
> trackCustom added to user-settings page

- apps/web/components/getting-started/steps-views/UserSettings.tsx
> rm: trackCustom

- apps/web/components/getting-started/steps-views/UserSettings.tsx
- apps/web/lib/fpixel.ts
> trackCustom added to userSettings

- apps/web/pages/index.tsx
> logout fixed

- apps/web/lib/event-types/getServerSideProps.tsx
- apps/web/pages/_app.tsx
- apps/web/pages/api/auth/keycloak/userinfo.ts
> ch: _app.tsx

- packages/features/auth/lib/next-auth-options.ts
- packages/features/bookings/components/PeopleFilter.tsx
Fix: Fixed bookings filter issue
> fix booking filter

- apps/web/modules/bookings/views/bookings-single-view.tsx
fix: booking page "try it for free" routes to cal.com
> fix: booking page "try it for free" routes to cal.com

- apps/web/pages/_document.tsx
removed pixel,clarity and gtm links from global level
> removed tracking links from global level

- packages/lib/customEvents.ts
> fix:default events for mentor

- packages/app-store/razorpay/lib/Razorpay.ts
- packages/sms/sms-manager.ts
Fixes:
1. Razorpay redirecttion fix for android devices
2. Team event type confirmation fix
> fix:razorpay and team eventtypes

- apps/web/modules/bookings/views/bookings-single-view.tsx
fix:booking confirmation on embed view
> fix:booking confirmation on embed view

- packages/features/oe/workflows/api/scheduleEmailReminders.ts
> email workflow scheduled fix

- apps/web/pages/index.tsx
- packages/features/shell/Shell.tsx
- packages/features/shell/navigation/Navigation.tsx
- packages/features/shell/navigation/NavigationItem.tsx
- packages/lib/hooks/useIsWebView.ts
written hook to hide certain features for mobile app
> chore: conditional view hook for mobile app

- apps/web/pages/api/import/calendly/index.ts
- packages/calendly/src/utils/calendly-service.ts
- packages/lib/timezone.ts
fix: issue while importing event booking field question of type "multiselect / select"
> fix:multi select field isuse from calendly booking

- packages/app-store/googlecalendar/api/webhook.ts
temporarily disabled gcal sync
> temporarily disbaled gcal sync

- packages/trpc/server/routers/viewer/workflows/update.schema.ts
fix:workflow creation issue due to zod type
> fix:workflow type fix

- packages/app-store/razorpay/lib/handleRazorpayOAuthRedirect.ts
Enabled razorpay webhook creation logic during razorpay integration
> fix:enabled razorpay webhook endpoint

- apps/web/pages/index.tsx
- packages/app-store/razorpay/api/webhook.ts
- packages/app-store/razorpay/lib/handleRazorpayPaymentRedirect.ts
chore:updated razorpay flow logic for handling webhooks
fix:enabled CORS for static asset icon path "/icons"
> Razorpay webhooks

- Dockerfile
- entrypoint.sh
- packages/lib/schedules/transformers/for-atom.ts
fix:changes in dockerfile to preserve node_modules
> fix:docker file changes

- .github/workflows/main-deploy.yml
- scripts/tunnel-rds.sh
chore:better management of images by utilizing separate ECR repos namely "cal_stag" and "cal_prod"
> chore:up-date aws repo name tagging

- scripts/tunnel-rds.sh
> updated tunneling  to be accessible by others user well

- .env.example
chore:added inngest signing key
> fix:added inngest signing key

- .github/workflows/main-deploy.yml
fixes checking out to prisma migrations directory in rollback step
> fix:sparse checkout in rollback step

- .github/workflows/main-deploy.yml
> feat: posthog prod config

- apps/web/pages/_document.tsx
> feat: added customer IO script

- .github/workflows/main-deploy.yml
Enabled manual image rebuilds, allowing redeployment when environment variables change without the need for dummy commits or pull requests.
> chore:added rebuild true params

- .github/workflows/main-deploy.yml
> fix: ci/cd workflow

- apps/web/app/settings/(admin-layout)/admin/users/[id]/edit/page.tsx
- apps/web/app/settings/(admin-layout)/admin/users/add/page.tsx
- apps/web/app/settings/(admin-layout)/admin/users/page.tsx
- apps/web/pages/api/trpc/users/[trpc].ts
- packages/features/auth/lib/next-auth-options.ts
- packages/features/ee/users/schemas/userBodySchema.ts
- packages/features/oe/impersonation/components/ImpersonatingBanner.tsx
- packages/features/oe/impersonation/lib/ImpersonationProvider.test.ts
- packages/features/oe/impersonation/lib/ImpersonationProvider.ts
- packages/features/oe/support/components/HelpMenuItem.tsx
- packages/features/oe/users/components/UserForm.tsx
- packages/features/oe/users/components/UsersTable.tsx
- packages/features/oe/users/pages/users-add-view.tsx
- packages/features/oe/users/pages/users-edit-view.tsx
- packages/features/oe/users/pages/users-listing-view.tsx
- packages/features/oe/users/schemas/userBodySchema.ts
- packages/features/oe/users/server/trpc-router.ts
- packages/features/shell/banners/LayoutBanner.tsx
- packages/trpc/server/routers/viewer/_router.tsx
OE implementation of : 
1. users management module
2. support components module
3. impersonation module
> feat: added support ,users and impersonation oe modules

- apps/web/middleware.ts
testing logic for blocking restricted subdomains
> chore:  subdomain blocking logic

- apps/web/middleware.ts
> fix:  subdomain blocking logic

- apps/web/middleware.ts
- infra/docker/web/nginx.template.conf
scraped nextjs middleware logic to redirect to authorized subdomains, using nginx now
> chore:switched to nginx for subdomain blocking

- apps/web/providers/session_providers.tsx
- packages/lib/hooks/useCustomerIO.ts
- packages/trpc/server/routers/loggedInViewer/myStats.handler.ts
improved session manager wrapper :
1. check for active keycloak session only on first page load rather than on each page change
2. attached more custom attributes to user for better tracking on analytics on platform
> feat: added additional user stats to analytics

- .github/workflows/docker-cleanup.yml
cron job for pruning older build images from docker hub
> fix:docker image prune cron

- apps/web/providers/session_providers.tsx
Updated date fields format as CIO supports epoch formatting.
> chore: updated user attribute date fields to epoch format

- apps/web/providers/session_providers.tsx
> chore : updated epochMilli to epochSecond

- apps/web/server/lib/auth/login/getServerSideProps.tsx
- packages/features/auth/lib/next-auth-options.ts
- packages/types/next-auth.d.ts
fixes: redirection issue during signup through manual signup link
> fix:redirection issue on signup through static link

- apps/web/providers/session_providers.tsx
name field stores email of user as well he they don't set there full name during onboarding, so I'm properly trying to fetch first and last name from the same.
> chore: properly retrieve first and last name from field name

- apps/web/pages/index.tsx
updated action of "Get started" button instead of hiding it
> chore:updated link ref of get started button instead of hiding it

- apps/web/lib/team/[slug]/getServerSideProps.tsx
- apps/web/modules/event-types/views/event-types-listing-view.tsx
- packages/features/flags/whitelist.config.ts
- packages/features/shell/navigation/Navigation.tsx
- packages/lib/hooks/useWhitelistCheck.ts
- packages/oe-features/workflows/view/components/workflow_list.tsx
- packages/oe-features/workflows/view/pages/workflow_editor_page.tsx
- packages/trpc/server/routers/viewer/eventTypes/getByViewer.schema.ts
- packages/trpc/server/routers/viewer/eventTypes/getUserEventGroups.handler.ts
1. fixes event bubbling issue on clicking workflow delete action
2. selective whitelisting for team public pages
3. whitelisting team event types
> Workflow with whitelist

- packages/app-store/googlecalendar/lib/CalendarService.ts
1.fixes mail being triggered from google calendar to attendee
> fix: google calendar sending email to attendee from their end

- packages/features/bookings/lib/getCalEventResponses.ts
- Do not show undefined phone field in Calendar events
> Fix: Calendar phone field

- apps/web/public/static/locales/en/common.json
- packages/features/eventtypes/components/Locations.tsx
- packages/lib/event-types/utils/locationsResolver.ts
1. made location mandatory for event type
> chore:added location check on event-type

- .gitignore
- apps/web/modules/bookings/views/bookings-single-view.tsx
- packages/emails/email-manager.ts
- packages/emails/src/templates/AttendeeScheduledEmail.tsx
- packages/emails/src/templates/BaseScheduledEmail.tsx
fix:attendee were still able to cancel/reschedule event even though it was disabled in event config
> fix:booking manage issue for attendee

- packages/features/auth/lib/next-auth-options.ts
allow cross oauth login for same email
> allow cross oauth login for same email

- apps/web/components/getting-started/steps-views/UserSettings.tsx
> fix:onboarding next step issue

- apps/web/modules/settings/my-account/profile-view.tsx
chore:use resusable phone field component on profile view page
> chore:reused new phone field component on profile page

- packages/features/auth/lib/next-auth-options.ts
github test email verify fetch
> test:gitauth

- .github/workflows/main-deploy.yml
fix delimiter issue on url replace in pipeline
> fix:delimiter issue on homepage url replace

- packages/emails/src/components/EmailBodyLogo.tsx
Hide Product logo from email template for now, replace with static Text Cal ID and reducing padding
> temp:base email template modify for logo

- apps/web/components/getting-started/steps-views/UserSettings.tsx
- apps/web/modules/settings/my-account/profile-view.tsx
- apps/web/pages/api/auth/keycloak/userinfo.ts
- apps/web/pages/api/import/calendly/index.ts
- packages/emails/src/templates/CalendlyCampaignEmail.tsx
- packages/emails/templates/calendly-campaign-email.tsx
- packages/features/form-builder/Components.tsx
- packages/oe-features/ui/components/PhoneNumberField.tsx
- packages/trpc/server/routers/publicViewer/countryCode.handler.ts
- Ensures the Phone field on the Profile Page and Onboarding Page correctly displays the “Number is Valid” badge.
- Displays the Booker’s country on the Booking Page.
- Updates the Calendly import email to show the correct Sleek URL.
> Fix: Phone validation , calendly mail, country code
